[package]
name = "internal-iterator"
version = "0.0.1"
authors = ["djade <djadenkus@gmail.com>"]
edition = "2018"
repository = "https://github.com/jDomantas/internal-iterator"
license = "MIT OR Apache-2.0"
description = "Internal iteration equivalent of `std::iter::Iterator`."

[dependencies]
